-- ============================================================================
-- 10 TIN CẬP NHẬT NGÀY HÔM NAY — LÀM PHONG PHÚ MỤC TIN TỨC
-- ============================================================================
--
-- Nội dung viết lại theo tinh thần các cảnh báo, thông báo thời sự đang lưu
-- hành (không sao chép nguyên văn từ bất kỳ nguồn nào), phù hợp giọng văn của
-- một đơn vị công an cấp thị xã. Đủ bốn nhóm: cảnh giác (5), an ninh trật tự
-- (2), hướng dẫn thủ tục (2), văn bản mới (1).
--
-- Ba tin đầu đánh dấu is_featured = 1 để hiện trong băng chuyền tin nổi bật.
--
-- ⚠️ Trước khi đăng thật, cán bộ phụ trách tin tức nên rà lại nội dung, đối
--    chiếu với thông báo chính thức của Công an tỉnh/thị xã và bổ sung số
--    liệu, địa chỉ, số điện thoại cụ thể nếu có.
--
-- CÁCH CHẠY: HeidiSQL -> chọn đúng database -> dán toàn bộ -> F9
-- ============================================================================

INSERT INTO news
  (title, summary, content, category, image_url, source_name, source_url,
   is_external, is_published, is_featured, published_at)
VALUES
('Bộ Công an cảnh báo 5 nhóm thủ đoạn lừa đảo trực tuyến phổ biến năm 2026', 'Công an tổng hợp năm nhóm thủ đoạn lừa đảo qua mạng đang diễn biến phức tạp, từ giả danh cơ quan chức năng tới dùng công nghệ AI giả giọng nói, hình ảnh người thân.', 'Theo cảnh báo mới nhất của lực lượng Công an, tội phạm lừa đảo chiếm đoạt tài sản trên không gian mạng tiếp tục diễn biến phức tạp với thủ đoạn ngày càng tinh vi. Năm nhóm thủ đoạn chính được nêu gồm: giả danh Công an, Viện kiểm sát, Tòa án, ngân hàng, nhà trường, bệnh viện để yêu cầu cung cấp mã OTP hoặc chuyển tiền; dùng công nghệ AI, giả giọng nói và hình ảnh người thân để vay tiền gấp; giả biên lai chuyển khoản trong giao dịch mua bán online; và phát tán đường link, mã QR độc hại để chiếm quyền điều khiển điện thoại.\n\nBà con lưu ý: bất kỳ ai tự xưng cán bộ, yêu cầu chuyển tiền hoặc đọc mã OTP qua điện thoại đều là dấu hiệu lừa đảo. Cán bộ thật không bao giờ làm việc đó qua điện thoại hay mạng xã hội.', 'warning', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 1, CURDATE()),
('Cảnh giác cuộc gọi giả danh công an yêu cầu "chuẩn hoá" thông tin căn cước cho trẻ em', 'Xuất hiện thủ đoạn gọi điện cho phụ huynh, thông báo dữ liệu căn cước của con em bị sai lệch để dẫn dụ cung cấp thông tin cá nhân.', 'Gần đây ghi nhận thủ đoạn mới: đối tượng giả danh cán bộ công an gọi điện cho phụ huynh, thông báo thông tin căn cước của con em "bị sai lệch" hoặc "chưa cập nhật" trên hệ thống, yêu cầu cung cấp thông tin cá nhân hoặc thao tác theo hướng dẫn qua điện thoại để "khắc phục".\n\nLợi dụng tâm lý lo lắng của phụ huynh, đối tượng dễ dàng khai thác được thông tin nhạy cảm. Bà con lưu ý: mọi thủ tục liên quan đến căn cước, kể cả của trẻ em, đều phải thực hiện trực tiếp tại cơ quan công an hoặc qua kênh chính thống, không có việc "chuẩn hoá qua điện thoại".', 'warning', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 1, CURDATE()),
('Cảnh giác chiêu giả danh công an gọi mời lên trụ sở "xác minh vi phạm"', 'Đối tượng tự xưng cán bộ điều tra, gọi điện đe doạ người dân liên quan vụ việc nghiêm trọng để yêu cầu hợp tác, cung cấp thông tin.', 'Thủ đoạn phổ biến: đối tượng gọi điện tự xưng là cán bộ công an, đọc đúng họ tên người nghe rồi thông báo họ liên quan tới một vụ việc vi phạm pháp luật, yêu cầu tới trụ sở hoặc cung cấp thông tin qua điện thoại để "xác minh, làm rõ". Khi bị hỏi lại cấp bậc, đơn vị công tác, đối tượng vẫn tự xưng rất rành mạch để tạo lòng tin, sau đó liên tục hối thúc, đe doạ khiến người nghe hoang mang làm theo.\n\nCông an khẳng định: mọi giấy mời, giấy triệu tập đều được gửi bằng văn bản có đóng dấu, giao trực tiếp hoặc qua công an địa phương, không mời làm việc qua điện thoại. Nhận được cuộc gọi như trên, bà con bình tĩnh, không cung cấp thông tin, và báo ngay công an nơi cư trú để được hướng dẫn.', 'warning', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 0, CURDATE()),
('Thủ đoạn giả biên lai chuyển khoản khi mua bán hàng qua mạng', 'Kẻ gian dùng ảnh chụp biên lai chuyển khoản đã chỉnh sửa để chiếm đoạt hàng mà không trả tiền, hoặc yêu cầu đặt cọc trước rồi biến mất.', 'Lợi dụng giao dịch mua bán qua mạng xã hội, một số đối tượng dùng biên lai chuyển khoản giả để yêu cầu người bán giao hàng trước khi thực tế chưa hề chuyển tiền. Ngược lại, cũng có trường hợp giả làm người bán, yêu cầu khách đặt cọc trước rồi chặn liên lạc, chiếm đoạt tiền cọc.\n\nBà con khi mua bán online nên kiểm tra kỹ số dư thực tế trước khi giao hàng, tránh giao dịch với người lạ yêu cầu đặt cọc số tiền lớn, và ưu tiên gặp trực tiếp với các giao dịch giá trị cao.', 'warning', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 0, CURDATE()),
('Cảnh giác đường link, mã QR lạ chiếm quyền điều khiển điện thoại', 'Kẻ gian phát tán đường link giả mạo hoặc mã QR độc hại, dụ người dùng cài ứng dụng chứa mã độc để chiếm tài khoản ngân hàng, mạng xã hội.', 'Một thủ đoạn đang lan rộng là gửi đường link hoặc mã QR qua tin nhắn, mạng xã hội với nội dung hấp dẫn như trúng thưởng, nhận hỗ trợ, tra cứu phạt nguội. Khi quét mã hoặc bấm vào link, người dùng bị dẫn tới trang cài đặt ứng dụng lạ chứa mã độc, từ đó đối tượng chiếm quyền điều khiển điện thoại, đọc trộm tin nhắn OTP và rút tiền trong tài khoản ngân hàng.\n\nBà con tuyệt đối không quét mã QR hoặc bấm vào link từ người lạ, không cài ứng dụng ngoài các kho ứng dụng chính thức. Nghi ngờ điện thoại bị cài mã độc thì ngắt kết nối mạng ngay và mang máy tới nơi sửa chữa uy tín kiểm tra.', 'warning', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 0, CURDATE()),
('Công an thị xã Tân Châu tăng cường tuần tra bảo đảm an ninh trật tự dịp cuối năm', 'Lực lượng công an cơ sở tăng cường tuần tra đêm tại các địa bàn trọng điểm, kịp thời ngăn chặn các vụ việc gây mất an ninh trật tự.', 'Nhằm bảo đảm an ninh trật tự trên địa bàn, Công an thị xã Tân Châu đã triển khai kế hoạch tăng cường tuần tra, kiểm soát vào khung giờ tối và đêm tại các tuyến đường, khu vực đông dân cư. Qua công tác tuần tra, lực lượng chức năng đã kịp thời phát hiện, nhắc nhở và xử lý một số trường hợp vi phạm liên quan tới trật tự công cộng.\n\nCông an thị xã đề nghị bà con tiếp tục phối hợp, kịp thời báo tin khi phát hiện dấu hiệu bất thường về an ninh trật tự tại địa bàn mình sinh sống, góp phần giữ gìn bình yên cho xóm ấp.', 'security', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 1, CURDATE()),
('Ra quân bảo đảm trật tự an toàn giao thông dịp lễ, Tết', 'Lực lượng chức năng đồng loạt kiểm tra, xử lý vi phạm về nồng độ cồn, tốc độ và các lỗi vi phạm giao thông khác trên các tuyến đường trọng điểm.', 'Thực hiện chỉ đạo bảo đảm trật tự an toàn giao thông trong các dịp cao điểm, lực lượng cảnh sát giao thông đã ra quân kiểm tra, xử lý nghiêm các hành vi vi phạm như điều khiển phương tiện sau khi uống rượu bia, chạy quá tốc độ, không đội mũ bảo hiểm. Việc kiểm tra được thực hiện đồng loạt tại nhiều tuyến đường trọng điểm nhằm kéo giảm tai nạn giao thông.\n\nBà con khi tham gia giao thông cần chấp hành nghiêm quy định, không điều khiển phương tiện khi đã uống rượu bia để bảo đảm an toàn cho bản thân và người xung quanh.', 'security', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 0, CURDATE()),
('Hướng dẫn thủ tục đăng ký tạm trú, tạm vắng qua ứng dụng VNeID', 'Người dân có thể thực hiện thủ tục đăng ký tạm trú, tạm vắng trực tuyến qua ứng dụng VNeID mà không cần tới trực tiếp trụ sở công an.', 'Để tạo thuận lợi cho người dân, thủ tục đăng ký tạm trú và khai báo tạm vắng hiện có thể thực hiện trực tuyến qua ứng dụng định danh điện tử VNeID. Người dân cần có tài khoản định danh mức 2, sau đó vào mục thủ tục hành chính, chọn đúng loại thủ tục cần đăng ký và làm theo hướng dẫn trên ứng dụng.\n\nTrường hợp chưa có tài khoản định danh điện tử hoặc gặp khó khăn khi thao tác, bà con có thể tới trực tiếp trụ sở Công an thị xã hoặc công an xã, phường nơi cư trú để được cán bộ hướng dẫn và hỗ trợ thực hiện.', 'guide', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 0, CURDATE()),
('Hướng dẫn các bước làm lại căn cước công dân khi mất hoặc hư hỏng', 'Người dân bị mất hoặc hỏng căn cước công dân cần chuẩn bị giấy tờ gì và thực hiện thủ tục ở đâu để được cấp lại nhanh chóng.', 'Trường hợp căn cước công dân bị mất, hư hỏng hoặc hết hạn, người dân đến trực tiếp cơ quan công an cấp huyện, thị xã nơi thường trú hoặc tạm trú để làm thủ tục cấp lại. Cần mang theo sổ hộ khẩu hoặc giấy tờ chứng minh nơi cư trú, và có thể đặt lịch hẹn trước qua tổng đài hoặc ứng dụng VNeID để giảm thời gian chờ.\n\nSau khi hoàn tất thủ tục, người dân sẽ nhận được giấy hẹn trả kết quả và có thể tra cứu tiến độ xử lý căn cước qua Cổng dịch vụ công.', 'guide', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 0, CURDATE()),
('Thông báo lịch tiếp công dân định kỳ của Công an thị xã Tân Châu', 'Công an thị xã bố trí lịch tiếp công dân định kỳ để lắng nghe phản ánh, kiến nghị và giải quyết các thủ tục hành chính.', 'Nhằm tạo điều kiện thuận lợi cho người dân trong việc phản ánh, kiến nghị cũng như giải quyết các thủ tục hành chính, Công an thị xã Tân Châu thông báo lịch tiếp công dân định kỳ vào các ngày làm việc trong tuần tại trụ sở đơn vị.\n\nBà con có nhu cầu phản ánh, kiến nghị hoặc cần hướng dẫn thủ tục có thể đến trực tiếp trụ sở trong giờ hành chính, hoặc gửi ý kiến qua Hộp Thư An Ninh Số để được tiếp nhận và xử lý theo đúng quy trình.', 'document', NULL, 'Công an thị xã Tân Châu', NULL, FALSE, TRUE, 0, CURDATE());

-- ============================================================================
-- KIỂM TRA SAU KHI CHẠY
-- ============================================================================
SELECT id, title, category, is_featured, published_at
  FROM news
 WHERE published_at = CURDATE()
 ORDER BY id DESC;
